apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sergetol/demo-frontend:1.0.1  # 1.0.0
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "dummy"
        - name: CURRENCY_SERVICE_ADDR
          value: "dummy"
        - name: CART_SERVICE_ADDR
          value: "dummy"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "dummy"
        - name: CHECKOUT_SERVICE_ADDR
          value: "dummy"
        - name: SHIPPING_SERVICE_ADDR
          value: "dummy"
        - name: AD_SERVICE_ADDR
          value: "dummy"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
