apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sergetol/demo-frontend:1.0.1  # 1.0.0
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            port: 8080
            path: "/_healthz"
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "dummy"
        - name: CURRENCY_SERVICE_ADDR
          value: "dummy"
        - name: CART_SERVICE_ADDR
          value: "dummy"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "dummy"
        - name: CHECKOUT_SERVICE_ADDR
          value: "dummy"
        - name: SHIPPING_SERVICE_ADDR
          value: "dummy"
        - name: AD_SERVICE_ADDR
          value: "dummy"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
