apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: sergetol/demo-frontend:1.0.0
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
