apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: sergetol/demo-frontend:1.0.0
    name: frontend
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "dummy"
    - name: CURRENCY_SERVICE_ADDR
      value: "dummy"
    - name: CART_SERVICE_ADDR
      value: "dummy"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "dummy"
    - name: CHECKOUT_SERVICE_ADDR
      value: "dummy"
    - name: SHIPPING_SERVICE_ADDR
      value: "dummy"
    - name: AD_SERVICE_ADDR
      value: "dummy"
    - name: ENV_PLATFORM
      value: "local"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
